### ISSUE TITLE
Profile paths that contain %SystemDrive% require special handling for artifact filters

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2327]
Windows XP user profile paths contain %SystemDrive% this requires an additional expansion when used in artifact filters

**Comment by joachimmetz** [comment]
So the artifact definition OperaHistory does not use %SystemDrive% but %%users.appdata%%

```
---
name: OperaHistory
doc: Opera browser history (global_history.dat).
sources:
- type: FILE
  attributes: {paths: ['%%users.homedir%%/Library/Opera//global_history.dat']}
  supported_os: [Darwin]
- type: FILE
  attributes: {paths: ['%%users.homedir%%/.opera/global_history.dat']}
  supported_os: [Linux]
- type: FILE
  attributes:
    paths:
      - '%%users.appdata%%\Opera\Opera\global_history.dat'
      - '%%users.appdata%%\Opera Software\Opera Stable\History'
    separator: '\'
  supported_os: [Windows]
supported_os: [Windows,Darwin,Linux]
labels: [Browser]
urls: ['http://www.forensicswiki.org/wiki/Opera']
```
